[project]
name = "ai-receptionist"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.136.1",
    "jq>=1.11.0",
    "langchain>=1.2.17",
    "langchain-chroma>=1.1.0",
    "langchain-community>=0.4.1",
    "langchain-openai>=1.2.1",
    "livekit>=1.1.7",
    "livekit-agents[deepgram,elevenlabs,groq,openai,resemble,silero]>=1.3.11",
    "pydantic>=2.13.3",
    "pydantic-settings>=2.14.0",
    "rank-bm25>=0.2.2",
]
